// PHASE 2 orchestrator — turn a CHOSEN notebook entry into a verified blog (+image)
// AND a LinkedIn post (BUILD_SPEC §12). All content is produced by the AIS model;
// the output gate guarantees nothing unsupported ships.
// Run: npm run generate ["output/notebook/<file>.json"]   (defaults to the latest)
import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import type { ResearchResult } from "./types";
import { getLLM } from "./llm";
import { draft } from "./agent/draft";
import { runOutputGate } from "./quality/outputGate";
import { generateIllustration } from "./image";
import { writeJson, slugify, clamp } from "./util";
import { writeFile, mkdir } from "node:fs/promises";
import { log } from "./log";

async function resolveNotebook(): Promise<string> {
  const arg = process.argv.slice(2).find((a) => !a.startsWith("--"));
  if (arg) return arg;
  const dir = "output/notebook";
  const files = (await readdir(dir)).filter((f) => f.endsWith(".json")).sort();
  const latest = files[files.length - 1];
  if (!latest) {
    console.error('No notebook entries found. Run `npm run research "topic"` first.');
    process.exit(1);
  }
  return join(dir, latest);
}

// Cheap reading-ease proxy (0–100): shorter sentences/words read easier.
function readability(md: string): number {
  const text = md.replace(/[#>*`_\-\[\]()]/g, " ");
  const sentences = text.split(/[.!?]+/).filter((s) => s.trim().length > 0);
  const words = text.split(/\s+/).filter(Boolean);
  if (!sentences.length || !words.length) return 0;
  const wps = words.length / sentences.length;
  const longWords = words.filter((w) => w.length > 7).length / words.length;
  return clamp(Math.round(110 - 1.2 * wps - 100 * longWords));
}

async function linkedinPost(r: ResearchResult, blogFile: string): Promise<string> {
  const out = await getLLM().complete(
    `Write a LinkedIn post (max ~1200 chars) about "${r.topic}".\nThesis: ${r.synthesis.thesis}\n` +
      `Key points:\n${r.synthesis.keyClaims.slice(0, 4).map((c) => `- ${c.claim}`).join("\n")}\n\n` +
      `Strong first-line hook, 3–4 short takeaways, a line pointing readers to the full blog ` +
      `(${blogFile}), and 3–5 relevant hashtags. No invented facts. Do not call any tools.`,
    { system: "You are a sharp LinkedIn writer for a technical audience." },
  );
  return out.trim();
}

async function main(): Promise<void> {
  const path = await resolveNotebook();
  const r = JSON.parse(await readFile(path, "utf8")) as ResearchResult;
  log.step(`PulseAI generate — "${r.topic}" (from ${path})`);

  // 1) draft → critique → revise
  const drafted = await draft(r);

  // 2) output gate: verify claims, cut unsupported
  const gate = await runOutputGate(drafted, r);

  // 3) illustration (best-effort, after verify)
  const imageUrl = await generateIllustration(r.topic);

  // 4) assemble blog
  const base = `${r.createdAt.slice(0, 10)}-${slugify(r.topic)}`;
  const blogFile = `output/drafts/${base}-blog.md`;
  const sourcesList = r.articles
    .map((a, i) => `- [S${i + 1}] [${a.title}](${a.url})`)
    .join("\n");
  const read = readability(gate.cleanDraft);
  const blog =
    `${imageUrl ? `![illustration](${imageUrl})\n\n` : ""}${gate.cleanDraft}\n\n` +
    `---\n\n## Sources\n${sourcesList}\n\n` +
    `---\n\n*Generated by PulseAI from a Phase 1 research entry (researchScore ${r.researchScore}, ` +
    `${r.articles.length} sources, ${r.rounds} round(s)). Output gate: factualSupport ` +
    `${gate.factualSupport}/100 across ${gate.checks.length} claims (${gate.unsupported.length} removed). ` +
    `Readability ${read}/100.*\n`;

  // 5) assemble LinkedIn
  const linkedin = await linkedinPost(r, blogFile);
  const linkedinFile = `output/drafts/${base}-linkedin.md`;

  await mkdir("output/drafts", { recursive: true });
  await writeFile(blogFile, blog, "utf8");
  await writeFile(linkedinFile, linkedin + "\n", "utf8");
  // a small machine-readable report next to the drafts
  await writeJson(`output/drafts/${base}-report.json`, {
    topic: r.topic,
    sourceNotebook: path,
    factualSupport: gate.factualSupport,
    readability: read,
    claims: gate.checks.length,
    removed: gate.unsupported.length,
    imageUrl,
    blogFile,
    linkedinFile,
  });

  log.ok(`blog → ${blogFile}`);
  log.ok(`linkedin → ${linkedinFile}`);
  log.ok(`factualSupport ${gate.factualSupport}/100, readability ${read}/100, image: ${imageUrl ? "yes" : "none"}`);
}

main().catch((e) => {
  log.error((e as Error).message);
  process.exit(1);
});
